modLoader="javafml"
loaderVersion="[35,)"
issueTrackerURL="https://github.com/noobanidus/wishingforsunshine/issues"
license="https://github.com/noobanidus/wishingforsunshine/blob/1.12/LICENSE"
[[mods]]
modId="wishingforsunshine"
version="${file.jarVersion}"
displayName="Wishing for Sunshine"
displayURL="https://minecraft.curseforge.com/projects/wishingforsunshine"
logoFile="logo.png"
authors="Noobanidus"
description='''
A craftable Wishing Well block that allows you to throw items into it in order to manipulate the time of day or the weather.
'''
[[dependencies.wishingforsunshine]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.wishingforsunshine]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,)"
    ordering="NONE"
    side="BOTH"